# Generated by Django 6.0.2 on 2026-02-23 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flux', '0002_alter_ticket_image_delete_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='description',
            field=models.TextField(max_length=8192),
        ),
    ]
