# Generated by Django 6.0.2 on 2026-03-02 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flux', '0003_alter_ticket_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='date_edited',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
