# Generated by Django 6.0.2 on 2026-03-26 14:03

import flux.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flux', '0008_alter_review_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='image',
            field=models.ImageField(upload_to=flux.models.ticket_image_path, verbose_name='Image'),
        ),
    ]
