# Generated by Django 6.0.2 on 2026-03-26 14:06

import flux.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flux', '0009_alter_ticket_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='image',
            field=models.ImageField(max_length=255, upload_to=flux.models.ticket_image_path, verbose_name='Image'),
        ),
    ]
