# Generated by Django 6.0.2 on 2026-03-27 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flux', '0010_alter_ticket_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='time_edited',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date de modification'),
        ),
    ]
