# Generated by Django 6.0.2 on 2026-03-02 15:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_user_follows'),
        ('flux', '0005_userfollows_user_userfollows_user_followed_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='follows',
        ),
        migrations.AddField(
            model_name='user',
            name='users_followed',
            field=models.ManyToManyField(related_name='followers', through='flux.UserFollows', to=settings.AUTH_USER_MODEL),
        ),
    ]
