# Generated by Django 6.0.2 on 2026-03-09 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_remove_user_follows_user_users_followed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='users_followed',
        ),
    ]
